### ISSUE TITLE
No such file or directory: 'pacman'

### ISSUE THREAD

**Issue by sakshemglaze** [israel-dryer/TkFontAwesome#4]
On mac os i tried to install this package using command pip install fontawesome but it give me error.

Collecting tkfontawesome
  Using cached tkfontawesome-0.2.0-py3-none-any.whl (405 kB)
Collecting tksvg==0.7.4
  Using cached tksvg-0.7.4.tar.gz (50 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Installing dependency cmake... Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/p2/_8dlzbbd3kq5wr0rmwd2xh600000gn/T/pip-install-qez1bb0p/tksvg_a96fbe2637684b8398caee99455febb7/setup.py", line 62, in <module>
          sp.call(["pacman", "--needed", "--noconfirm", "-S", "mingw-w64-x86_64-{}".format(dep)])  # , stdout=sp.PIPE)
        File "/usr/local/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 349, in call
          with Popen(*popenargs, **kwargs) as p:
        File "/usr/local/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/local/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'pacman'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by israel-dryer** [comment]
It appears the underlying library [tksvg](https://pypi.org/project/tksvg/) is only available on Windows & Linux... though it appears the [tcl version is available for mac](https://github.com/oehhar/tksvg/releases), the python library author has not configured for that.

**Comment by sakshemglaze** [comment]
So now can we discontinue this tool because we need this for mac system?

**Comment by israel-dryer** [comment]
No need to discontinue. It still works perfectly fine at the moment for Linux and Windows.

**Comment by chrisdel101** [comment]
Also tried to use on mac 12.4 : `No such file or directory: 'pacman': 'pacman'`. Is there any workaround to get it to work?
